### ISSUE TITLE
Upload on Packagist?

### ISSUE THREAD

**Issue by keithmifsud** [container-interop/compiler-interop#1]
Do you intend to upload this on packagist for version better version control or not yet?

I'd like to start with implementing the interfaces to see what issues I'll find. I'm doing the same with the other interop (soon to be ) standards :) and it would be helpful to be able to update any approved PRs from composer since my packages will then depend on it.

**Comment by mnapoli** [comment]
Hi! This package is currently in a frozen state, we are working on a different solution that you can find here: https://github.com/container-interop/service-provider

**Comment by keithmifsud** [comment]
@mnapoli Thanks. Not sure if I am missing something or if the plans have changed; will you be trying to have an interop compiler that will be able to retrieve cached bindings if the cache exist? I don't think this is related to the service provider proposed standards.

**Comment by moufmouf** [comment]
Hey Keith,

The end goal is to be able to put things in any container in a cross-framework compatible way.
This package was really our first attempt. Since then, we have been making many other tests (see http://www.thecodingmachine.com/psr-11-an-overview-of-interoperable-php-modules/).

We are currently working hard on  https://github.com/container-interop/service-provider because it is the most promising way to do things. It is easy to implement in both compiled and runtime containers.

Therefore, this package is really frozen.
Yet, I used it as a base to my compiler: https://github.com/thecodingmachine/yaco

You can see the interface here:
- https://github.com/thecodingmachine/yaco/blob/1.0/src/Definition/DumpableInterface.php

As you can see, I'm not returning PHP Code, but an object containing this PHP code:

https://github.com/thecodingmachine/yaco/blob/1.0/src/Definition/InlineEntryInterface.php

This is because I want to be able to inline some private definitions.

If you are interested, I'd be happyt to put those 2 interfaces in a separate package so we can share those compilable definitions, but that would really be only the 2 of us. The work right now is really focused on https://github.com/container-interop/service-provider that may become a PSR.

**Comment by keithmifsud** [comment]
@moufmouf  Thanks for your reply :) I will get back to this later on this week and will reply in full then.

**Comment by mnapoli** [comment]
Closing the issue then! :)
